version: '3'

services:
  node:
    build: ./docker/node
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app
    command: /bin/bash -c "cd reactapp && npm start"
    ports:
    - "3000:3000"